apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-keycloak
  template:
    metadata:
      labels:
        app: postgres-keycloak
    spec:
      containers:
      - name: postgres-keycloak
        image: postgres:10-alpine
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: keycloak
          - name: POSTGRES_DB
            value: keycloak
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-keycloak-secret
                key: POSTGRES_PASSWORD
        volumeMounts:
        - name: postgres-keycloak-volume
          mountPath: /var/lib/pgsql/data
      volumes:
      - name: postgres-keycloak-volume
        persistentVolumeClaim:
          claimName: postgres-keycloak-pvc
